// <auto-generated />
namespace IntroToEntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedorderdateanddescription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedorderdateanddescription));
        
        string IMigrationMetadata.Id
        {
            get { return "201802212109387_added order date and description"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
